name: Website

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - "website/**"
      - "docs/**"
      - "README.md"
      - "CONTRIBUTING.md"
      - "**/README.md"
      - "**/CHANGELOG.md"
      - ".github/workflows/website.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Lint, typecheck & build docs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: website/package-lock.json

      - run: npm ci
      - run: npm run lint
      - run: npm run types:check
      - run: npm run build
